title: Born2bewild
subtitle: Orang-Utans in die Freiheit!
email: email@born2bewild.org
description: > # this means to ignore newlines until "baseurl:"
  Mit Tastatur, Fotoapparat und Kamera kämpft Nicola Walpen für das Überleben der Borneo Orang-Utans.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://born2bewild.org" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
youtube_username: nicolawalpen

# Build settings
excerpt_separator: <!--more-->
markdown: kramdown
theme: minima
# gems:
#   - jekyll-feed
#   - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
